name: deltiecord
description: A lightweight Matrix client with an old-school desktop focus.
publish_to: none
version: 0.2.3+14

environment:
  sdk: ^3.13.0

dependencies:
  file_picker: ^11.0.2
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_quill: ^11.5.1
  html: ^0.15.6
  flutter_vodozemac: ^0.7.1
  matrix: ^10.0.1
  media_kit: ^1.2.6
  media_kit_libs_video: ^1.0.7
  media_kit_video: ^2.0.1
  mime: ^2.0.0
  path: ^1.9.1
  path_provider: ^2.1.6
  sqflite: ^2.4.3
  sqflite_common_ffi: ^2.4.2
  vodozemac: ^0.7.0
  vsc_quill_delta_to_html: ^1.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
